#!/bin/bash
sudo apt-get update
sudo apt-get install docker.io -y
sudo sysctl vm.max_map_count=262144
sudo docker pull sebp/elk
sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -d --name elk sebp/elk
sudo /opt/logstash/bin/logstash-plugin install logstash-input-http_poller
